### PR TITLE
feat: Add NanoGPT provider integration

### PR DESCRIPTION
**Pull request by jcrabapple**
## Summary
This PR adds comprehensive support for the NanoGPT API provider to LastChat.

## Features
- ✅ Chat completions using OpenAI-compatible API
- ✅ Image generation support  
- ✅ Embedding model support
- ✅ Balance checking functionality
- ✅ Web search integration via NanoGPT Search API

## Changes
- New `NanoGPTProvider` class with full API implementation
- NanoGPT provider settings and configuration UI
- `NanoGPTSearchService` for web search capabilities
- Updated all when expressions to handle NanoGPT provider type
- Made `ModelRegistry.CLAUDE_4_5` public for test accessibility
- Fixed syntax errors in `ProviderSetting.kt` and `NanoGPTSearchService.kt`

## Testing
- ✅ Debug build compiles successfully
- ✅ Release build compiles successfully
- ✅ All exhaustive when expression errors fixed
- ✅ APK generated and ready for testing

### Provider Features
The NanoGPT provider supports:
- **Chat API**: OpenAI-compatible chat completions endpoint
- **Image Generation**: Support for multiple image models (FLUX, HiDream, Recraft, DALL-E, SDXL)
- **Embeddings**: Text embedding generation
- **Balance Checking**: Built-in balance query support with custom API path configuration

### Search Integration
The NanoGPT Search service provides:
- Web search with configurable depth
- Multiple output formats (searchResults, sourcedAnswer, structured)
- URL scraping functionality
- Image results support

### Code Quality
- All compilation errors resolved
- Proper error handling and null safety
- Follows existing codebase patterns and conventions
- Includes co-author attribution as required

Co-Authored-By: Warp <agent@warp.dev>

### CODE REVIEW

**Comment by Cocolalilal** [comment]
Adding a Nano-GPT class is a bit redundant since it can already be set up by choosing the OpenAI type and changing the API Paths and URLs. But I'll rework how adding new providers works in 1.1.9, NanoGPT will be a preset there, along with other presets. I'll also add the NanoGPT search service as an option. Thank you for the pull request!
